version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  sails:
    build: .
    ports:
      - "1337:1337"
    volumes:
      - ./:/server
    command: sails lift
    environment:
      - NODE_ENV=dev
    restart: always
    depends_on:
      - db
